server:
  port: 8081
  context-path: /invest
spring:
  devtools:
    restart:
      additional-paths: applayer/invest/src/main/java
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: false