server:
  port: 8082
  context-path: /operation
  connection-timeout: 60000
  maxHttpPostSize: 10485760
management:
  port: 3032
  context-path: /turbine
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: false
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
hystrix:
  command:
    default:
     execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  OkToRetryOnAllOperations: false
  ReadTimeout: 30000
  ConnectTimeout: 30000